blogvlog/blog/urls.py
from django.urls import path, include
from blog import urls
from . import views

urlpatterns = [
    path('', views.Homepage.as_view(), name='homepage'),
    path('aboutus', views.AboutUs.as_view(), name="aboutus"),
    path('post/<int:pk>', views.PostDetail, name='postdetail'),
    path('newpost', views.newpost, name='newpost'),
    path('usrinfo', views.user_image_func, name='usrinfo'),
    path('postedit/<int:pk>', views.PostEdit.as_view(), name='postedit'),
    path('postdelete/<int:pk>', views.BlogDelete.as_view(), name='postdelete'),
    path('mypost/<author>', views.MyPost.as_view(), name='myposts'),
    path('commentreplydelete/<int:pk>', views.CommentReplyDelete.as_view(), name='commentreplydelete'),
    path('commentdelete/<int:pk>', views.CommentDelete.as_view(), name='commentdelete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('post/postnew', views.BlogPostNew.as_view(), name='postnew'),
    path('profile/<str:nam>', views.profile, name='profile'),
    path('editprofileinfo/<int:pk>', views.userInfoFormView, name='editprofileinfo'),
    path('search', views.search, name='search'),
    path('category/<str:hashtags>', views.categoryview, name='category'),

]

blogvlog/trynewblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogvlog/blog/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
import os
from PIL import Image

# Create your models here.

class Hashtag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


def get_topbanner_filename(instance, filename):
    title = instance.title
    slug = slugify(title)
    return "documents/banner/{}/{}".format(slug, filename)

class Blog(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=200, null=True, blank=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    text = models.TextField()
    date = models.DateField(auto_now_add=True, blank=True, null=True)
    star = models.PositiveIntegerField(default=0)
    topbanner =  models.ImageField(upload_to=get_topbanner_filename, null=True, blank=True)
    category  = models.ForeignKey(Hashtag,  on_delete=models.CASCADE, null=True, blank=True)
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('postdetail', args=[str(self.id)])

#, default='documents/03.jpg'


def get_image_filename(instance, filename):
    title = instance.blog.id
    slug = slugify(title)
    return "post_images/post_images_{}/{}".format(slug, filename)


class Document(models.Model):
    blog = models.ForeignKey(Blog, default=None, on_delete=models.CASCADE)
    image = models.FileField(upload_to=get_image_filename, verbose_name = 'Image')

    def filename(self):
        return os.path.basename(self.image.name)

#-----------------------------------------------------------

def get_user_image_filename(instance, filename):
    title = instance.author
    slug = slugify(title)
    return "user_image_{}/{}".format(slug, filename)

class UserImage(models.Model):
    author = models.OneToOneField('auth.User', on_delete=models.CASCADE, null=True, default=True)
    myimage = models.ImageField(upload_to=get_user_image_filename, default='user_image_noimg/jobs.jpg', null=True, blank=True)


#------------------------------------------------------

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    message = models.CharField(max_length = 250)
    usrimg = models.ForeignKey(UserImage, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.message


class CommentReply(models.Model):
    whichcomment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    message = models.CharField(max_length = 250)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    usrimg = models.ForeignKey(UserImage, on_delete=models.CASCADE, null=True, blank=True)

    

    def __str__(self):
        return self.message





#------------------------------------------------------

class UserInfo(models.Model):
    author = models.OneToOneField('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    displayname = models.CharField(max_length=50, null=True, blank=True)
    designation = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    views = models.PositiveIntegerField(default = 0)

    def get_absolute_url(self):
        return reverse('homepage')

#-------------------------------------------------------

blogvlog/blog/forms.py
from .models import Comment, CommentReply, Blog, Document, UserImage, UserInfo
from django.forms import ModelForm, ImageField, FileField
from PIL import Image
from django import forms
from django.core.files.images import get_image_dimensions
from django.core.files import File
from simple_search import search_form_factory


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        exclude = ('date', 'star', 'author',)

class DocumentForm(ModelForm):
    image = FileField(label='Image')
    class Meta:
        model = Document
        fields = ('image', )

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

class CommentReplyForm(ModelForm):
    class Meta:
        model = CommentReply
        fields = ['message']


class UserImageForm(ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = UserImage
        fields = ('myimage','x', 'y', 'width', 'height')


    def save(self):
        photo = super(UserImageForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.myimage)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.myimage.path)

        return photo

class UserInfoForm(ModelForm):
    email = forms.EmailField()
    class Meta:
        model = UserInfo
        exclude = ('author', 'views')
        fields = ('displayname', 'designation', 'description', 'birthdate', 'email')
#        fields = '__all__'

blogvlog/templates/base.html
<!DOCTYPE html>
<html >
<head>
  <!-- Site made with Mobirise Website Builder v4.7.0, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.7.0, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  {% load static %}
  <link rel="shortcut icon" href="{% static 'assets/images/logo2.png' %}" type="image/x-icon">
  <meta name="description" content="Web Site Maker Description">
  <title>homepage</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
  
<style>
.hashtagsinp:hover{
    text-decoration: underline;
}
</style>
  
</head>  


<body>

{% load static %}
<script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
<script src="{% static 'assets/popper/popper.min.js' %}"></script>
<script src="{% static 'assets/tether/tether.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
<script src="{% static 'assets/dropdown/js/script.min.js' %}"></script>
<script src="{% static 'assets/touchswipe/jquery.touch-swipe.min.js' %}"></script>
<script src="{% static 'assets/theme/js/script.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/shortcuts/infinite.js"></script>


  <section class="menu cid-qOrcLPjtgR" once="menu" id="menu1-h">
    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{% url 'homepage' %}">
                        {% load static %}
                         <img src="{% static 'assets/images/TIGER-res.png' %}" alt="" title="" style="height: 3.8rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="{% url 'homepage' %}">BlogVlog</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">

                <li class="nav-item">
                    <form class="form-inline" method="GET" action="{% url 'search' %}">

                        <input class="form-control mr-sm-2" id="id_q" name="q" type="search" placeholder="Search Blog" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </li>

                <li class="nav-item dropdown open">
                        <a class="nav-link link text-white display-4" data-toggle="modal" data-target="#categoryModal" href="#">
                            <span class="mbri-setting2 mbr-iconfont mbr-iconfont-btn"></span>
                                Category
                        </a>
        
                </li>
                <li class="nav-item">
                    <a class="nav-link link text-white display-4" href="{% url 'aboutus' %}">
                        <span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                        About Us
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown open">
                        <a class="nav-link link text-white dropdown-toggle display-4" href="https://mobirise.com" data-toggle="dropdown-submenu" aria-expanded="true">
                            <span class="mbri-smile-face mbr-iconfont mbr-iconfont-btn"></span>
                            {{ request.user.first_name|truncatechars:22 }}
                        </a>
                        <div class="dropdown-menu">
                            <a class="text-white dropdown-item display-4" href="{% url 'profile' request.user %}">Profile</a>
                            
                            <a class="text-white dropdown-item display-4" href="{% url 'newpost' %}">New Post</a>
                           <hr>
                            <a class="btn btn-sm btn-warning display-4" href="{% url 'logout' %}">
                                <span class="mbri-play mbr-iconfont mbr-iconfont-btn"></span>
                                    Logout
                            </a>
                        </div>
                    </li>
                
                {% else %}
                <li>
                <a class="btn btn-sm btn-primary display-4" href="{% url 'login' %}">
                    <span class="mbri-play mbr-iconfont mbr-iconfont-btn"></span>
                    Login
                </a>
            </li>
                {% endif %}
        </ul>
        </div>
    </nav>
</section>


{% block body %}

{% endblock %}

<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Category</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% for hashtags in hashtag %}
                <a href="{% url 'category' hashtags%}" class="hashtagsinp">&nbsp;#{{hashtags}}&nbsp;&nbsp;</a>
            {% endfor %}
                    </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal" style="padding:4%;">Close</button>
        </div>
        </div>
    </div>
</div>

blogvlog/templates/basecrop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.css" rel="stylesheet">
    
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.js"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

blogvlog/templates/blogdelete.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
<button type="submit">submit</button>
</form>

blogvlog/templates/blogedit.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
<button type="submit">submit</button>
</form>

blogvlog/templates/categoryview.html
{% extends 'base.html' %}

{% block body %}
<style>

@media (min-width: 576px){
    .jumbotron {
     padding: 2%;
    }
}

</style>
<br><br><br><br>

{% if err %}
<div class="row">
    <div class="col-sm-10 offset-sm-1">
        <h2 class="text-center">{{err}}</h2>
    </div>
</div>

{% endif %}






    <div class="container-fluid">
        <div class="card-columns">
                <div class="infinite_container">
            {% for post in object_list %}
            <div class="card border border-dark">
                    <a href="{% url 'postdetail' post.pk %}">
                        <img class="card-img-top" src="/media/{{ post.topbanner}}" alt="Card image cap">
                    </a>

                <div class="card-body">
                    <a href="{% url 'postdetail' post.pk %}"><h4 class="card-title">{{ post.title }}</h4></a>
                    <p class="card-text"><a href="{% url 'postdetail' post.pk %}" class="text-black">{% autoescape off %}{{post.text|truncatechars:100}}{% endautoescape %}</a></p>
                    <div class="row">
                        <div class="col-xs-9 col-sm-9">
                            <p class="card-text"><small class="text-muted">written by <a href="" class="text-black">{{ post.author.first_name }}</a></small></p>
                        </div>
                        <div class="col-xs-3 col-sm-3">
                                <p class="card-text text-right"><small class="text-muted"><a href="" class="text-black"><span class="badge badge-primary"># {{ post.category }}</span> </a></small></p>
                        </div>
</div>            </div></div>

            {% endfor %}
</div>
        </div>
    </div>
 




</body>
</html>



{% endblock %}



{% if posts.has_other_pages  %}
<div class="row">
    <div class="col-sm-12 col-md-8 offset-md-2">
    <br>
<ul class="pagination justify-content-center">
    {% if posts.has_previous %}
        <li  class="page-item"><a  class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>    
        </a></li>
    {% else %}
        <li class='disabled page-item'> <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a><li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active"><span><a class="page-link" href="?page={{i}}">{{ i }} </a></span></li>
        {% else %}
            <li  class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
        {% endif %}
    {% endfor %}
    {% if posts.has_next %}
        <li><a class="page-link"  href="?page={{ page_obj.next_page_number }}"> <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span></a></li>
    {% else %}
        <li class="disabled page-item"><a href=""  class="page-link" ><span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span></a></li>
    {% endif %}
</ul>
{% endif %}

blogvlog/templates/homepagee.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
    <div class="cell-12">
            
        <a href="#" class="brand">Brand name</a>
        <a href="#" class="brand no-hover">Brand name</a>

    </div>
</div>
<br>
<hr>

<hr>
<h3><a href="{% url 'postnew' %}">New Post</a></h3>
<br>

{% for post in object_list %}

<h1><a href="{% url 'postdetail' post.pk %}">{{ post.title }}</a></h1><span><a href="{% url 'postedit' post.pk %}"><u>edit</u></a></span>

<h4><a href="{% url 'myposts' post.author %}">{{ post.author }}</a></h4>
<p>{{ post.text }}</p>
<br>
{% endfor %}

{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class='disabled'><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} (curent page)</span></li>
            {% else %}
                <li><a href="?page={{i}}">{{i}}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}




<br>







    <h1 class="text-center">Metro 4</h1>
    <h3 class="text-center">The Components Library</h3>

{% endblock %}

blogvlog/templates/mypost.html
<a href="{% url 'homepage' %}">Homepage</a>
<br><hr>
<h2>my post</h2>

{% for post in authorallpost %}
<h2><a href="{% url 'postdetail' post.pk %}">{{ post.title }}</a></h2>

<p>{{ post.text }}</p>
{% endfor %}

<hr>

blogvlog/templates/profile.html
{% extends 'base.html' %}

{% block body %}
<link href="https://fonts.googleapis.com/css?family=Black+Han+Sans" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Hi+Melody" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.css" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
{% load static %}
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.js"></script>

<script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_myimage").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $('#formUpload').submit()
      });

    });
  </script>


<style>
  html, body{
    width: 100%;
    overflow-x: hidden;
  }

  input[type="file"] {
    display: none;
}

.uploadimagebutton{
  cursor: pointer;
}
</style>
<br><br><br><br>
<div class="row">
  <div class="col-sm-12 col-md-4 col-lg-4 " style="background: linear-gradient(30deg, white, 52%, white, 10px, rgb(255, 210, 126));">
    <div class="text-center">
      <img src="/media/{{data.myimage}}" class="img-fluid" style="border-radius:50%; " height=70% width="70%" alt="">
    </div>
    <!-- change picture form here-->
    {% if request.user == mainuser %}
  <div style="position: absolute; top:2%; right:2%">
    <form method="POST" enctype="multipart/form-data" id="formUpload">
      {% csrf_token %}
        <label for="id_myimage" class="uploadimagebutton"><span class="badge badge-primary"><span class="mbri-upload"></span> Change Image</span></label>
        <input type="file" id="id_myimage", name="myimage">
        <input type="hidden" id="id_x" name="x">
        <input type="hidden" id="id_y" name="y">
        <input type="hidden" id="id_width" name="width">
        <input type="hidden" id="id_height" name="height">        
        
    </form>
</div>
{% endif %}

  </div>
  <div class="col-sm-12 col-md-8 col-lg-8">
    <br>
    <div class="row">
        <div class="col-sm-12 col-md-6">
      <h1 class="text-capitalize " style="font-family: 'Black Han Sans', sans-serif;">{{ userinfo.displayname }}
          {% if request.user == mainuser %}
          <a href="{% url 'editprofileinfo' mainuser.pk %}" style="font-size: 1rem; font-family:'Courier New', Courier, monospace;" class="align-middle"><span class=" align-middle badge badge-primary"><span class="mbri-setting3"></span> edit info </span> </a>
          {% endif %}
      </h1>
      <h5 class="">{{ userinfo.designation }}</h5>
      </div>

    <div class="col-md-6">
        <div class="d-none d-md-block">
         <h1 class="float-md-right mr-5"><span class="mbri-edit"></span><span style="font-family: 'Black Han Sans', sans-serif;"> 32 </span><span style="font-size:1.2rem;">articles</span></h1>
      </div>
   </div>
    
    </div>
      <div class="row">
        <div class="col-sm-12 col-md-6">
      <div class="pt-5">
      <blockquote>{{ userinfo.description }}</blockquote>
      </div>
    </div>
    <div class="col-md-6">
        <div class="d-none d-md-block mt-4">
         <h1 class="float-md-right mr-5"><span class="mbri-preview"></span><span style="font-family: 'Black Han Sans', sans-serif;"> {{ userinfo.views }} </span><span style="font-size:1.2rem;">views</span></h1>
      </div>
   </div>
  
  </div>
  <div class="row">
    <div class="col-sm-12">
        <div class=" d-sm-block d-md-none d-xl-none ">
          <div class="row">
            <div class="col-sm-6">
            <h1 class="float-md-right mr-5"><span class="mbri-edit"></span><span style="font-family: 'Black Han Sans', sans-serif;"> 32 </span><span style="font-size:1rem;">articles</span></h1>
            </div>
            <div class="col-sm-6">
            <h1 class="float-md-right mr-5"><span class="mbri-preview"></span><span style="font-family: 'Black Han Sans', sans-serif;"> {{ userinfo.views }} </span><span style="font-size:1rem;">views</span></h1>
              </div>
              </div>
          </div>
    </div>
  </div>

</div>
</div>
<hr>
<div class="row">
    <div class="col-sm-12">
      <h2 class="text-center">~ Articles ~</h2>
    </div>
  </div>
  <hr>
<div class="row">

    <div class="container-fluid">
        <div class="card-columns">
            
            {% for post in blogs %}
            <div class="card border border-dark">
                    <a href="{% url 'postdetail' post.pk %}">
                        <img class="card-img-top" src="{{ post.topbanner.url }}" alt="Card image cap">
                    </a>

                <div class="card-body">
                    <a href="{% url 'postdetail' post.pk %}"><h4 class="card-title">{{ post.title }}</h4></a>
                    <p class="card-text"><a href="{% url 'postdetail' post.pk %}" class="text-black">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</a></p>
                    <p class="card-text text-right"><small class="text-muted">written by <a href="" class="text-black">{{ post.author }}</a></small></p>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>





<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>zoom in
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>zoom out
            </button>
          </div>
          <button type="button" class="btn btn-primary js-crop-and-upload">Done</button>
        </div>
      </div>
    </div>
  </div>



{% endblock %}

blogvlog/templates/signup.html
<h2>Sign up</h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Sign up</button>
</form>