blogvlog/blog/urls.py
from django.urls import path, include
from blog import urls
from . import views

urlpatterns = [
    path('', views.Homepage.as_view(), name='homepage'),
    path('aboutus', views.AboutUs.as_view(), name="aboutus"),
    path('post/<int:pk>', views.PostDetail, name='postdetail'),
    path('newpost', views.newpost, name='newpost'),
    path('usrinfo', views.user_image_func, name='usrinfo'),
    path('postedit/<int:pk>', views.PostEdit.as_view(), name='postedit'),
    path('postdelete/<int:pk>', views.BlogDelete.as_view(), name='postdelete'),
    path('mypost/<author>', views.MyPost.as_view(), name='myposts'),
    path('commentreplydelete/<int:pk>', views.CommentReplyDelete.as_view(), name='commentreplydelete'),
    path('commentdelete/<int:pk>', views.CommentDelete.as_view(), name='commentdelete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('post/postnew', views.BlogPostNew.as_view(), name='postnew'),
    path('profile/<str:nam>', views.profile, name='profile'),
    path('editprofileinfo/<int:pk>', views.userInfoFormView, name='editprofileinfo'),
    path('search', views.search, name='search'),
    path('category/<str:hashtags>', views.categoryview, name='category'),

]

blogvlog/trynewblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogvlog/blog/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
import os
from PIL import Image

# Create your models here.

class Hashtag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


def get_topbanner_filename(instance, filename):
    title = instance.title
    slug = slugify(title)
    return "documents/banner/{}/{}".format(slug, filename)

class Blog(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=200, null=True, blank=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    text = models.TextField()
    date = models.DateField(auto_now_add=True, blank=True, null=True)
    star = models.PositiveIntegerField(default=0)
    topbanner =  models.ImageField(upload_to=get_topbanner_filename, null=True, blank=True)
    category  = models.ForeignKey(Hashtag,  on_delete=models.CASCADE, null=True, blank=True)
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('postdetail', args=[str(self.id)])

#, default='documents/03.jpg'


def get_image_filename(instance, filename):
    title = instance.blog.id
    slug = slugify(title)
    return "post_images/post_images_{}/{}".format(slug, filename)


class Document(models.Model):
    blog = models.ForeignKey(Blog, default=None, on_delete=models.CASCADE)
    image = models.FileField(upload_to=get_image_filename, verbose_name = 'Image')

    def filename(self):
        return os.path.basename(self.image.name)

#-----------------------------------------------------------

def get_user_image_filename(instance, filename):
    title = instance.author
    slug = slugify(title)
    return "user_image_{}/{}".format(slug, filename)

class UserImage(models.Model):
    author = models.OneToOneField('auth.User', on_delete=models.CASCADE, null=True, default=True)
    myimage = models.ImageField(upload_to=get_user_image_filename, default='user_image_noimg/jobs.jpg', null=True, blank=True)


#------------------------------------------------------

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    message = models.CharField(max_length = 250)
    usrimg = models.ForeignKey(UserImage, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.message


class CommentReply(models.Model):
    whichcomment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    message = models.CharField(max_length = 250)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    usrimg = models.ForeignKey(UserImage, on_delete=models.CASCADE, null=True, blank=True)

    

    def __str__(self):
        return self.message





#------------------------------------------------------

class UserInfo(models.Model):
    author = models.OneToOneField('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    displayname = models.CharField(max_length=50, null=True, blank=True)
    designation = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    views = models.PositiveIntegerField(default = 0)

    def get_absolute_url(self):
        return reverse('homepage')

#-------------------------------------------------------

blogvlog/templates/tuesday/comment.html
<div class="">
    
    <li><a href="">{{ comment.author }}</a>
        -
        {{ comment.message |safe }} - {% if comment.parent %} -My id -{{comment.id}}{% else %}None{% endif %}
        <br>
        <form method='POST' id="comment-form">
            {% csrf_token %}
            <input type="text" name="parent" id="id_parent" value="{{comment.id}}">
            <label for="id_message">Message:</label>
            <input type="text" name="message" id="id_message">
            <button id="ajaxbut">Submit by ajax</button>
            <button type='submit'>Submit</button>
        </form>
</li>

    {% if comment.replies %}
        {% for comment in comment.replies.all %}
        <div style="margin-left:15px"> {% include 'tuesday/comment.html' %} </div>
        {% endfor %}
    {% endif %}
</div>


<script>

    $('#ajaxbut').onClick(function(){
        $.ajax({
            type:"POST",
            url:"{% url 'tuesday' %}",
            data:{"message":$("#id_message").val(), "parent":$("#id_parent").val()},
            beforeSend:function(xhr){
                xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));  
            },
            success:function(data,textStatus){
                $("#id_message").val("");
                $(".comment ul").prepend(data);
            },
            error:function(XMLHttpRequest, textStatus, errorThrown){
                alert(XMLHttpRequest.responseText);
    
            }
    
        });
        return false;
    });
</script>

blogvlog/templates/tuesday/tuesday.html
<h1>tuesday</h1>
<hr>
<a href="{% url 'login' %}">Login</a>/ <a href="{% url 'homepage' %}">Homepage</a>
<br><hr>
<h3>add new comment</h3>
<form method='POST'>
    {% csrf_token %}
    <label for="id_message">Message</label>
    <input type="text" name='message' id="id_message">
    <button type='submit'>Submit</button>
</form><br><hr style="color: red"><br>
<div class="comment">
<ul>
{% for comment in data %}
    {% include 'tuesday/comment.html' %}
    <hr>
{% endfor %}
</ul>
</div>